version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 8080:5432
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=zenskar
  